name: payment_test
description: A codelab for in-app purchases
publish_to: "none"
version: 1.0.0+8

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  in_app_purchase: ^3.0.8
  intl: ^0.17.0
  provider: ^6.0.4

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
